packages:
  - 'packages/*'

catalog:
  "@biomejs/biome": "1.9.4"
  "@types/react": "19.0.0"
  "@types/node": "22.13.4"
  "@tamagui/animations-moti": "1.125.8"
  "@tamagui/build": "1.125.8"
  "@tamagui/colors": "1.125.8"
  "@tamagui/constants": "1.125.8"
  "@tamagui/helpers-icon": "1.125.8"
  "@tamagui/theme-builder": "1.125.8"
  "react": "19.0.0"
  "react-native": "0.76.5"
  "react-native-reanimated": "3.16.5"
  "react-native-safe-area-context": "4.10.5"
  "react-native-screens": "4.4.0"
  "react-native-svg": "15.8.0"
  "react-native-web": "0.19.12"
  "tamagui": "1.125.8"
  "typescript": "5.7.3"
