packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  "@biomejs/biome": "1.9.4"
  "@types/react": "18.3.18"
  "@types/node": "22.13.4"
  "@tamagui/animations-moti": "1.125.14"
  "@tamagui/build": "1.125.14"
  "@tamagui/colors": "1.125.14"
  "@tamagui/constants": "1.125.14"
  "@tamagui/helpers-icon": "1.125.14"
  "@tamagui/lucide-icons": "1.125.14"
  "@tamagui/theme-builder": "1.125.14"
  "react": "18.3"
  "react-native": "0.76.5"
  "react-native-reanimated": "3.16.5"
  "react-native-safe-area-context": "4.10.5"
  "react-native-screens": "4.4.0"
  "react-native-svg": "15.8.0"
  "react-native-web": "0.19.12"
  "tamagui": "1.125.14"
  "typescript": "5.7.3"

catalogs:
  one:
    "one": "1.1.450"
    "@react-native-community/cli": "15.1.3"
    "@tamagui/vite-plugin": "1.125.14"
    "vite": "6.1.0"
    "@vxrn/color-scheme": "1.1.450"
    "expo": "52.0.17"
    "expo-modules-core": "2.1.2"

