
compressionLevel: mixed
enableGlobalCache: false
enableTelemetry: false
nodeLinker: node-modules

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
